project:
  type: website
  output-dir: docs

website:
  title: "Yellow Island 2024"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: Week.qmd
        text: Weekly Schedule
      - href: projects.qmd
        text: Projects
      - href: mentorship.qmd
        text: Mentorship
      - href: resources.qmd
        text: Resources
      - icon: github
        href: https://github.com/ChrisMantegna
      - icon: twitter
        href: https://twitter.com/SaffireSeahorse
format:
  html:
    theme: pulse
    css: styles.css

editor: visual
