---
title: "Weekly Schedule at a Glance"
format:
  html:
    toc: true
html_dependencies:
  - name: "bootstrap"
    version: "4.3.1"
    src: "https://stackpath.bootstrapcdn.com"
    stylesheet: "bootstrap.min.css"
    script: "bootstrap.min.js"
---

## Week 1

This week it's all REU all the time while we await our DDCSP folks and their summer orientation in Seattle

| Date | Task                                                                  |
|------------------|------------------------------------------------------|
| 6/10 | Welcome to FHL Orientation, Day 1 of 2, Meet your mentor              |
| 6/11 | Welcome to FHL Orientation, Day 2 of 2                                |
| 6/12 | Jackson Beach Seining, Independent work, FHL Seminar, Mentor check-in |
| 6/13 | Bottom Trawl, Independent work                                        |
| 6/14 | Mentor check-in, VGIGHL, Independent work                             |
| 6/15 | Day off                                                               |
| 6/16 | Day off                                                               |

## Week 2

Whole cohort activities!

| Date | Task                                                                                            |
|------------------|------------------------------------------------------|
| 6/17 | Welcome to FHL DDCSP, REU 1v1s, Community guidelines, Cooking schedule, What is the intertidal? |
| 6/18 | Professional development, FHL Seminar                                                           |
| 6/19 | Site survey forms, Species ID, what to expect, eet a Scientist w/ Dr. Stanton Belford           |
| 6/20 | Meet Yellow                                                                                     |
| 6/21 | Project proposals and idea generation for all, Ecology skill builder                            |
| 6/22 | Yellow field day                                                                                |
| 6/23 | Yellow field day                                                                                |

## Week 3

Whole cohort activities!

| Date | Task                                                             |
|------|------------------------------------------------------------------|
| 6/24 | Yellow field day                                                 |
| 6/25 | Yellow field day, bonus Naturalist?                              |
| 6/26 | REU 1v1s,Meet a Scientist- Dr. Kolisa Yola Sinyana, FHL Seminar  |
| 6/27 | Prep work for Stanton,Data entry from surveys                    |
| 6/28 | Stanton Skill Builder, Chris leaves, data entry for survey       |
| 6/29 | Data entry, projects, day off (Chris off island)                 |
| 6/30 | Whale watching, data entry, projects, day off (Chris off island) |

## Week 4

Whole cohort activities!

| Date | Task                                                                                    |
|------------------|------------------------------------------------------|
| 7/01 | Data entry must be complete by today, projects, day off. Chris returning to island (pm) |
| 7/02 | Yellow field day                                                                        |
| 7/03 | Yellow field day                                                                        |
| 7/04 | Yellow field day                                                                        |
| 7/05 | Yellow field day                                                                        |
| 7/06 | Yellow field day                                                                        |
| 7/07 | Chris off island                                                                        |

## Week 5

Whole cohort activities!

| Date | Task                                           |
|------|------------------------------------------------|
| 7/08 | (Chris returning to island), KPJ Skill Builder |
| 7/09 | Professional Development                       |
| 7/10 | REU 1v1s, Alt Careers Panel                    |
| 7/11 | DDCSP 1v1s                                     |
| 7/12 | DDCSP Camping                                  |
| 7/13 | DDCSP Camping                                  |
| 7/14 | DDCSP Camping                                  |

## Week 6

Whole cohort activities!

| Date | Task                                                       |
|------|------------------------------------------------------------|
| 7/15 | DDCSP Camping                                              |
| 7/16 |                                                            |
| 7/17 | REU 1v1s, DDCSP 1v1s, Chris is the FHL Seminar             |
| 7/18 | Yellow Field Day                                           |
| 7/19 | Yellow Field Day                                           |
| 7/20 | Yellow Field Day                                           |
| 7/21 | FINAL Yellow Day, gratitude, pictures (Chris leave island) |

## Week 7

Whole cohort activities!

| Date | Task                              |
|------|-----------------------------------|
| 7/22 | Chris off island                  |
| 7/23 | Chris off island                  |
| 7/24 | REU 1v1s, DDCSP 1v1s, FHL Seminar |
| 7/25 |                                   |
| 7/26 | Grad Panel                        |
| 7/27 |                                   |
| 7/28 |                                   |

## Week 8

Whole cohort activities!

| Date | Task                            |
|------|---------------------------------|
| 7/29 |                                 |
| 7/30 | REU Presentations, Chris leaves |
| 7/31 |                                 |
| 8/01 |                                 |
| 8/02 | Final REU Day                   |
| 8/03 | REUs travel home                |
| 8/04 |                                 |

## Week 9

DDCSP activities!

| Date | Task                    |
|------|-------------------------|
| 8/05 | DDCSP Cohort in Seattle |
| 8/06 | DDCSP Cohort in Seattle |
| 8/07 | DDCSP Cohort in Seattle |
| 8/08 | DDCSP Cohort in Seattle |
| 8/09 | DDCSP Summit            |
| 8/10 | DDCSP Travel home       |
| 8/11 | DDCSP Travel home       |
